# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
  pull_request:
    branches: [master]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install autopep8
          pip install -r requirement.txt
        working-directory: ./backend

      - name: Formatting with autopep8
        run: |
          autopep8 --in-place --aggressive --aggressive -r .
        working-directory: ./backend

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ./backend

      - name: Slack Notification Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: "#5cb85c"
          SLACK_TITLE: "Success to Deploy to GitHub Pages :rocket:"
          SLACK_MESSAGE: ":closed_book: ${{ github.repository }}"

      - name: Slack Notification Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: "#dc143c"
          SLACK_TITLE: "Failure to Deploy to GitHub Pages :boom:"
          SLACK_MESSAGE: ":closed_book: ${{ github.repository }}"
