on:
  push:
    branches:
      - master
    paths:
      - "front/**"

name: Deploy React application to AWS S3

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      #       - name: Make config.json
      #         env:
      #           CONFIG_JSON: ${{ secrets.FRONT_CONFIG_JSON }}
      #         run: |
      #           touch front/src/config.json
      #           echo ${CONFIG_JSON} > front/src/config.json

      - name: Package Install
        run: yarn install
        working-directory: ./front

      - name: Build
        run: yarn run build
        working-directory: ./front
        env:
          CI: ""

      - name: Publish to AWS S3 & CloudFront
        uses: opspresso/action-s3-sync@v0.2.3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: "./front/build"
          DEST_PATH: ${{ secrets.AWS_S3_BUCKET_PATH }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: "#5cb85c"
          SLACK_TITLE: "Success to Deploy to GitHub Pages :rocket:"
          SLACK_MESSAGE: ":closed_book: ${{ github.repository }}"

      - name: Slack Notification Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: "#dc143c"
          SLACK_TITLE: "Failure to Deploy to GitHub Pages :boom:"
          SLACK_MESSAGE: ":closed_book: ${{ github.repository }}"
